apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy.cloud.kuly/app: storage-redis
  name: storage-redis
  namespace: kuly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy.cloud.kuly/app: storage-redis
  template:
    metadata:
      labels:
        deploy.cloud.kuly/app: storage-redis
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: storage-redis
        ports:
        - containerPort: 12270
          name: rpc
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "12270"
        - name: REDIS_ADDRESS
          value: {{ .Values.redis.address }}
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.password }}
        - name: CONTROL_PLANE_HOST
          value: control-plane
        - name: CONTROL_PLANE_PORT
          value: "12270"
        resources: {}
